server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/retirement?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: warn
    org.springframework.web: debug
    org.hibernate: error

# App
app:
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}
  mail:
    from: ${APP_MAIL_FROM:no-reply@retirement.local}
